server:
  port: 8080

logging:
  level:
    org.springframework.web: ERROR
    boot: DEBUG
    dao: DEBUG
    datafetcher: DEBUG
    service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"