server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017

logging:
  level:
    org.springframework.web: ERROR
    aop: DEBUG
    boot: DEBUG
    domain: DEBUG
    service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

