server:
  port: 8080

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
  level:
    org.springframework.web: ERROR
    boot: DEBUG
    aop: DEBUG
    service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"