server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/clientdt?useSSL=false
    username: usuariocli
    password: senhacli
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

logging:
  level:
    org.springframework.web: ERROR
    boot: DEBUG
    service: DEBUG
    aop: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

